import React, { createContext, useState, useContext, useEffect } from 'react';
import api from '../lib/axios';

const LanguageContext = createContext();

const translations = {
    English: {
        welcome: "Welcome back",
        plan: "Your adventure awaits. What's the plan today?",
        explore: "Explore",
        newTrip: "Plan New Trip",
        totalBudget: "Total Planned Budget",
        totalTrips: "Total Trips",
        avgCost: "Avg. Trip Cost",
        recentTrips: "Recent Trips",
        viewAll: "View All",
        recommended: "Recommended for you",
        dashboard: "Dashboard",
        myTrips: "My Trips",
        profile: "Profile",
        logout: "Logout",
        save: "Save",
        savedDest: "Saved Destinations",
        deleteAccount: "Delete Account",
        editProfile: "Edit Profile",
        noTrips: "You haven't planned any trips yet.",
        startAdventure: "Start your first adventure",
        manageItinerary: "Manage Itinerary",
        confirmDeleteAccount: "Are you sure you want to delete your account? This cannot be undone.",
        failedToDeleteAccount: "Failed to delete account",
        loadingProfile: "Loading profile...",
        userIcon: "User Icon",
        noEmail: "No email",
        client: "CLIENT",
        english: "English",
        spanish: "Spanish",
        french: "French",
        german: "German",
        chinese: "Chinese",
        preview: "Preview",
        fullName: "Full Name",
        languagePreference: "Language Preference",
        cancel: "Cancel",
        saveChanges: "Save Changes",
        remove: "Remove",
        noSavedDestinations: "No saved destinations yet.",
        accountActions: "Account Actions",
        deleteAccountWarning: "Deleting your account will permanently remove all your trips and data.",
        user: "User",
        manageAdventures: "Manage all your planned adventures.",
        destinations: "Destinations",
        budgetLabel: "Budget:",
        deleteTrip: "Delete Trip",
        editTrip: "Edit Trip",
        startPlanning: "Start Planning",
        tripName: "Trip Name",
        tripDescPlaceholder: "e.g., Summer in Europe 2024",
        description: "Description",
        descPlaceholder: "Briefly describe your trip...",
        startDate: "Start Date",
        endDate: "End Date",
        estBudget: "Estimated Budget",
        coverPhoto: "Cover Photo (Optional)",
        creating: "Creating...",
        updateTrip: "Update Trip",
        planNewTrip: "Plan a New Trip",
        updateTripDetails: "Update your trip details.",
        startJourney: "Start your journey by defining the basics.",
        itinerary: "Itinerary",
        budget: "Budget",
        calendar: "Calendar",
        tripItinerary: "Trip Itinerary",
        addDestination: "Add Destination",
        addStop: "Add a new stop",
        city: "City",
        searchCity: "Search city...",
        arrival: "Arrival",
        departure: "Departure",
        saveStop: "Save Stop",
        removeStopConfirm: "Remove this stop?",
        activities: "Activities",
        addActivity: "Add Activity",
        noActivities: "No activities planned yet.",
        startItinerary: "Start your itinerary",
        addFirstDest: "Add your first destination to get started.",
        activityName: "Activity Name",
        cost: "Cost ($)",
        category: "Category",
        saveActivity: "Save Activity",
        costDist: "Cost Distribution",
        budgetOverview: "Budget Overview",
        totalExpenses: "Total Expenses",
        remaining: "Remaining",
        tripTimeline: "Trip Timeline",
        noStopsTimeline: "No stops to show on timeline.",
        exploreDest: "Explore Destinations",
        findPerfectCity: "Find the perfect city for your next adventure.",
        searchCityPlaceholder: "Search for a city (e.g., Paris, Tokyo)...",
        costIndex: "Cost Index:",
        cityDescDefault: "Discover the beauty and culture of this amazing destination.",
        planTripHere: "Plan a Trip Here",
        noCitiesFound: "No cities found matching",
        loginWelcome: "Welcome Back",
        loginSubtitle: "Sign in to continue to GlobeTrotter",
        emailLabel: "Email Address",
        emailPlaceholder: "you@example.com",
        passwordLabel: "Password",
        passwordPlaceholder: "••••••••",
        forgotPassword: "Forgot password?",
        signIn: "Sign In",
        noAccount: "Don't have an account?",
        createAccount: "Create account",
        createAccountTitle: "Create Account",
        verifyEmailTitle: "Verify Email",
        signupSubtitle: "Start your journey with GlobeTrotter",
        verifySubtitle: "One last step to get started",
        googleSignupFailed: "Google Signup Failed",
        orSignupEmail: "Or sign up with email",
        orLoginEmail: "Or continue with email",
        enterOtp: "Enter OTP",
        otpPlaceholder: "Enter 6-digit code",
        verifyActivate: "Verify & Activate",
        alreadyAccount: "Already have an account?",
        passRequirements: "Must contain 8+ chars, 1 uppercase, 1 number, 1 special char.",

        // New Additions
        dailySpending: "Daily Spending",
        noDailyData: "No daily data available",
        costDistribution: "Cost Distribution",
        transport: "Transport",
        other: "Other",
        accommodation: "Accommodation",
        food: "Food",
        shopping: "Shopping",
        sightseeing: "Sightseeing",
        adventure: "Adventure",
        relaxation: "Relaxation",
        flight: "Flight",
        train: "Train",
        bus: "Bus",
        car: "Car",
        interactiveCalendar: "Interactive Calendar",
        timeline: "Timeline",
        arrivingBy: "Arriving by",
        day: "Day",
        days: "Days",
        yourItineraryEmpty: "Your itinerary is empty. Go to the dashboard to add destinations!",
        noItineraryData: "No itinerary data.",
        startYourJourney: "Start your journey",
        haventAddedDestinations: "You haven't added any destinations yet. Click \"Add Destination\" above to begin planning your trip!",
        deleteActivityQuestion: "Delete Activity?",
        deleteActivityConfirm: "Are you sure you want to remove this activity? This action cannot be undone.",
        removeDestinationQuestion: "Remove Destination?",
        removeDestinationConfirm: "Are you sure you want to remove this destination? All associated activities will be deleted.",
        editActivity: "Edit Activity",
        addNewActivity: "Add New Activity",
        editDestination: "Edit Destination",
        confirm: "Confirm",
        cancel: "Cancel",
        type: "Type",
        notesOptional: "Notes (Optional)",
        cityName: "City Name",
        updateDestination: "Update Destination",
        unknownCity: "Unknown City",
        clickToAddActivity: "+ Add Activity",
        deleteTripQuestion: "Are you sure you want to delete this trip?",
        draft: "Draft",
        planned: "Planned",
        manageItineraryArrow: "Manage Itinerary →",
        noTripsFound: "No trips found",
        noTripsFound: "No trips found",
        youHaventPlanned: "You haven't planned any trips yet.",
        acrossActiveTrips: "Across all active trips",
        newRecently: "+ New recently",
        perItinerary: "Per itinerary",
        noRecommendations: "No specific recommendations yet. Explore to find more!",
        startTime: "Start Time",
        endTime: "End Time",
        dailySpending: "Daily Spending",
        noDailyData: "No daily data available",
        costDistribution: "Cost Distribution",
        transport: "Transport",
        other: "Other",
        accommodation: "Accommodation",
        food: "Food",
        shopping: "Shopping",
        sightseeing: "Sightseeing",
        adventure: "Adventure",
        relaxation: "Relaxation",
        flight: "Flight",
        train: "Train",
        bus: "Bus",
        car: "Car",
        interactiveCalendar: "Interactive Calendar",
        timeline: "Timeline",
        arrivingBy: "Arriving by",
        day: "Day",
        days: "Days",
        yourItineraryEmpty: "Your itinerary is empty. Go to dashboard to add destinations!",
        noItineraryData: "No itinerary data.",
        startYourJourney: "Start your journey",
        haventAddedDestinations: "You haven't added any destinations yet. Click \"Add Destination\" above to begin planning!",
        deleteActivityQuestion: "Delete Activity?",
        deleteActivityConfirm: "Are you sure you want to remove this activity? This cannot be undone.",
        removeDestinationQuestion: "Remove Destination?",
        removeDestinationConfirm: "Are you sure you want to remove this destination? All associated activities will be deleted.",
        editActivity: "Edit Activity",
        addNewActivity: "Add New Activity",
        editDestination: "Edit Destination",
        confirm: "Confirm",
        cancel: "Cancel",
        type: "Type",
        notesOptional: "Notes (Optional)",
        cityName: "City Name",
        updateDestination: "Update Destination",
        unknownCity: "Unknown City",
        clickToAddActivity: "+ Add Activity",
        deleteTripQuestion: "Are you sure you want to delete this trip?",
        draft: "Draft",
        planned: "Planned",
        manageItineraryArrow: "Manage Itinerary →",
        noTripsFound: "No trips found",
        youHaventPlanned: "You haven't planned any trips yet.",
        acrossActiveTrips: "Across all active trips",
        newRecently: "+ New recently",
        perItinerary: "Per itinerary",
        noRecommendations: "No specific recommendations yet. Explore to find more!"
    },
    Hindi: {
        welcome: "वापसी पर स्वागत है",
        plan: "आपका रोमांच इंतजार कर रहा है। आज की क्या योजना है?",
        explore: "अन्वेषण करें",
        newTrip: "नई यात्रा की योजना बनाएं",
        totalBudget: "कुल नियोजित बजट",
        totalTrips: "कुल यात्राएं",
        avgCost: "औसत यात्रा लागत",
        recentTrips: "हाल की यात्राएं",
        viewAll: "सभी देखें",
        recommended: "आपके लिए अनुशंसित",
        dashboard: "डैशबोर्ड",
        myTrips: "मेरी यात्राएं",
        profile: "प्रोफ़ाइल",
        logout: "लॉग आउट",
        save: "सहेजें",
        savedDest: "सहेजे गए गंतव्य",
        deleteAccount: "खाता हटाएं",
        editProfile: "प्रोफ़ाइल संपादित करें",
        noTrips: "आपने अभी तक कोई यात्रा योजना नहीं बनाई है।",
        startAdventure: "अपना पहला साहसिक कार्य शुरू करें",
        manageItinerary: "यात्रा कार्यक्रम प्रबंधित करें",
        confirmDeleteAccount: "क्या आप वाकई अपना खाता हटाना चाहते हैं? यह पूर्ववत नहीं किया जा सकता।",
        failedToDeleteAccount: "खाता हटाने में विफल",
        loadingProfile: "प्रोफ़ाइल लोड हो रही है...",
        userIcon: "उपयोगकर्ता आइकन",
        noEmail: "कोई ईमेल नहीं",
        client: "ग्राहक",
        english: "अंग्रेज़ी",
        hindi: "हिन्दी",
        tamil: "तमिल",
        telugu: "तेलुगु",
        malayalam: "मलयालम",
        kannada: "कन्नड़",
        preview: "पूर्वावलोकन",
        fullName: "पूरा नाम",
        languagePreference: "भाषा वरीयता",
        cancel: "रद्द करें",
        saveChanges: "परिवर्तन सहेजें",
        remove: "हटाएं",
        noSavedDestinations: "अभी तक कोई सहेजा गया गंतव्य नहीं है।",
        accountActions: "खाता कार्रवाई",
        deleteAccountWarning: "अपना खाता हटाने से आपकी सभी यात्राएं और डेटा स्थायी रूप से हटा दिया जाएगा।",
        user: "उपयोगकर्ता",
        manageAdventures: "अपनी सभी नियोजित रोमांच प्रबंधित करें।",
        destinations: "गंतव्य",
        budgetLabel: "बजट:",
        deleteTrip: "यात्रा हटाएं",
        editTrip: "यात्रा संपादित करें",
        startPlanning: "योजना शुरू करें",
        tripName: "यात्रा का नाम",
        tripDescPlaceholder: "जैसे, यूरोप में समर 2024",
        description: "विवरण",
        descPlaceholder: "अपनी यात्रा का संक्षेप में वर्णन करें...",
        startDate: "प्रारंभ तिथि",
        endDate: "समाप्ति तिथि",
        estBudget: "अनुमानित बजट",
        coverPhoto: "कवर फोटो (वैकल्पिक)",
        creating: "बना रहा है...",
        updateTrip: "यात्रा अपडेट करें",
        planNewTrip: "एक नई यात्रा की योजना बनाएं",
        updateTripDetails: "अपनी यात्रा विवरण अपडेट करें।",
        startJourney: "मूल बातें परिभाषित करके अपनी यात्रा शुरू करें।",
        itinerary: "यात्रा कार्यक्रम",
        budget: "बजट",
        calendar: "कैलेंडर",
        tripItinerary: "यात्रा कार्यक्रम",
        addDestination: "गंतव्य जोड़ें",
        addStop: "एक नया पड़ाव जोड़ें",
        city: "शहर",
        searchCity: "शहर खोजें...",
        arrival: "आगमन",
        departure: "प्रस्थान",
        saveStop: "पड़ाव सहेजें",
        removeStopConfirm: "इस पड़ाव को हटाएं?",
        activities: "गतिविधियां",
        addActivity: "गतिविधि जोड़ें",
        noActivities: "अभी तक कोई गतिविधि नियोजित नहीं है।",
        startItinerary: "अपना यात्रा कार्यक्रम शुरू करें",
        addFirstDest: "शुरू करने के लिए अपना पहला गंतव्य जोड़ें।",
        activityName: "गतिविधि का नाम",
        cost: "लागत ($)",
        category: "श्रेणी",
        saveActivity: "गतिविधि सहेजें",
        costDist: "लागत वितरण",
        budgetOverview: "बजट अवलोकन",
        totalExpenses: "कुल व्यय",
        remaining: "शेष",
        tripTimeline: "यात्रा समयरेखा",
        noStopsTimeline: "समयरेखा पर दिखाने के लिए कोई पड़ाव नहीं।",
        exploreDest: "गंतव्यों का अन्वेषण करें",
        findPerfectCity: "अपने अगले साहसिक कार्य के लिए सही शहर खोजें।",
        searchCityPlaceholder: "शहर खोजें (जैसे, पेरिस, टोक्यो)...",
        costIndex: "लागत सूचकांक:",
        cityDescDefault: "इस अद्भुत गंतव्य की सुंदरता और संस्कृति की खोज करें।",
        planTripHere: "यहाँ यात्रा की योजना बनाएं",
        noCitiesFound: "कोई मेल खाता शहर नहीं मिला",
        loginWelcome: "वापसी पर स्वागत है",
        loginSubtitle: "GlobeTrotter पर जारी रखने के लिए साइन इन करें",
        emailLabel: "ईमेल पता",
        emailPlaceholder: "apka@email.com",
        passwordLabel: "पासवर्ड",
        passwordPlaceholder: "••••••••",
        forgotPassword: "पासवर्ड भूल गए?",
        signIn: "साइन इन करें",
        noAccount: "खाता नहीं है?",
        createAccount: "खाता बनाएं",
        createAccountTitle: "खाता बनाएं",
        verifyEmailTitle: "ईमेल सत्यापित करें",
        signupSubtitle: "GlobeTrotter के साथ अपनी यात्रा शुरू करें",
        verifySubtitle: "शुरू करने के लिए एक आखिरी कदम",
        googleSignupFailed: "Google साइनअप विफल रहा",
        orSignupEmail: "या ईमेल के साथ साइन अप करें",
        orLoginEmail: "या ईमेल के साथ जारी रखें",
        enterOtp: "OTP दर्ज करें",
        otpPlaceholder: "6-अंकीय कोड दर्ज करें",
        verifyActivate: "सत्यापित करें और सक्रिय करें",
        alreadyAccount: "क्या पहले से ही खाता है?",
        passRequirements: "8+ वर्ण, 1 अपरकेस, 1 संख्या, 1 विशेष वर्ण होना चाहिए।",

        // New Additions
        dailySpending: "दैनिक खर्च",
        noDailyData: "कोई दैनिक डेटा उपलब्ध नहीं",
        costDistribution: "लागत वितरण",
        transport: "परिवहन",
        other: "अन्य",
        accommodation: "आवास",
        food: "भोजन",
        shopping: "खरीदारी",
        sightseeing: "दर्शनीय स्थल",
        adventure: "रोमांच",
        relaxation: "विश्राम",
        flight: "विमान",
        train: "ट्रेन",
        bus: "बस",
        car: "गाड़ी",
        interactiveCalendar: "इंटरैक्टिव कैलेंडर",
        timeline: "समयरेखा",
        arrivingBy: "द्वारा आगमन",
        day: "दिन",
        days: "दिन",
        yourItineraryEmpty: "आपका यात्रा कार्यक्रम खाली है। गंतव्य जोड़ने के लिए डैशबोर्ड पर जाएं!",
        noItineraryData: "कोई यात्रा कार्यक्रम डेटा नहीं।",
        startYourJourney: "अपनी यात्रा शुरू करें",
        haventAddedDestinations: "आपने अभी तक कोई गंतव्य नहीं जोड़ा है। अपनी यात्रा की योजना शुरू करने के लिए ऊपर \"गंतव्य जोड़ें\" पर क्लिक करें!",
        deleteActivityQuestion: "गतिविधि हटाएं?",
        deleteActivityConfirm: "क्या आप वाकई इस गतिविधि को हटाना चाहते हैं? यह पूर्ववत नहीं किया जा सकता।",
        removeDestinationQuestion: "गंतव्य हटाएं?",
        removeDestinationConfirm: "क्या आप वाकई इस गंतव्य को हटाना चाहते हैं? सभी संबंधित गतिविधियां हटा दी जाएंगी।",
        editActivity: "गतिविधि संपादित करें",
        addNewActivity: "नई गतिविधि जोड़ें",
        editDestination: "गंतव्य संपादित करें",
        confirm: "पुष्टि करें",
        cancel: "रद्द करें",
        type: "प्रकार",
        notesOptional: "नोट्स (वैकल्पिक)",
        cityName: "शहर का नाम",
        updateDestination: "गंतव्य अपडेट करें",
        unknownCity: "अज्ञात शहर",
        clickToAddActivity: "+ गतिविधि जोड़ें",
        deleteTripQuestion: "क्या आप वाकई इस यात्रा को हटाना चाहते हैं?",
        draft: "ड्राफ्ट",
        planned: "नियोजित",
        manageItineraryArrow: "यात्रा कार्यक्रम प्रबंधित करें →",
        noTripsFound: "कोई यात्रा नहीं मिली",
        noTripsFound: "कोई यात्रा नहीं मिली",
        youHaventPlanned: "आपने अभी तक कोई यात्रा योजना नहीं बनाई है।",
        acrossActiveTrips: "सभी सक्रिय यात्राओं में",
        newRecently: "+ हाल ही में नया",
        perItinerary: "प्रति यात्रा कार्यक्रम",
        noRecommendations: "अभी तक कोई सिफारिश नहीं। अधिक खोजने के लिए अन्वेषण करें!",
        startTime: "शुरुआत का समय",
        endTime: "समाप्ति का समय",
        dailySpending: "दैनिक खर्च",
        noDailyData: "दैनिक डेटा उपलब्ध नहीं",
        costDistribution: "लागत वितरण",
        transport: "परिवहन",
        other: "अन्य",
        accommodation: "आवास",
        food: "भोजन",
        shopping: "खरीदारी",
        sightseeing: "विहार",
        adventure: "साहसिक",
        relaxation: "विश्राम",
        flight: "उड़ान",
        train: "ट्रेन",
        bus: "बस",
        car: "कार",
        interactiveCalendar: "इंटरैक्टिव कैलेंडर",
        timeline: "समयरेखा",
        arrivingBy: "से आगमन",
        day: "दिन",
        days: "दिन",
        yourItineraryEmpty: "आपकी यात्रा कार्यक्रम खाली है। गंतव्यों को जोड़ने के लिए डैशबोर्ड पर जाएं!",
        noItineraryData: "कोई यात्रा डेटा नहीं।",
        startYourJourney: "अपनी यात्रा शुरू करें",
        haventAddedDestinations: "आपने अभी तक कोई गंतव्य नहीं जोड़ा है। योजना शुरू करने के लिए ऊपर \"गंतव्य जोड़ें\" पर क्लिक करें!",
        deleteActivityQuestion: "गतिविधि हटाएं?",
        deleteActivityConfirm: "क्या आप वाकई इस गतिविधि को हटाना चाहते हैं? इसे पूर्ववत नहीं किया जा सकता।",
        removeDestinationQuestion: "गंतव्य हटाएं?",
        removeDestinationConfirm: "क्या आप वाकई इस गंतव्य को हटाना चाहते हैं? सभी संबंधित गतिविधियां हटा दी जाएंगी।",
        editActivity: "गतिविधि संपादित करें",
        addNewActivity: "नई गतिविधि जोड़ें",
        editDestination: "गंतव्य संपादित करें",
        confirm: "पुष्टि करें",
        cancel: "रद्द करें",
        type: "प्रकार",
        notesOptional: "नोट्स (वैकल्पिक)",
        cityName: "शहर का नाम",
        updateDestination: "गंतव्य अपडेट करें",
        unknownCity: "अज्ञात शहर",
        clickToAddActivity: "+ गतिविधि जोड़ें",
        deleteTripQuestion: "क्या आप वाकई इस यात्रा को हटाना चाहते हैं?",
        draft: "ड्राफ्ट",
        planned: "नियोजित",
        manageItineraryArrow: "यात्रा कार्यक्रम प्रबंधित करें →",
        noTripsFound: "कोई यात्रा नहीं मिली",
        youHaventPlanned: "आपने अभी तक कोई यात्रा योजना नहीं बनाई है।",
        acrossActiveTrips: "सभी सक्रिय यात्राओं में",
        newRecently: "+ हाल ही में नया",
        perItinerary: "प्रति यात्रा कार्यक्रम",
        noRecommendations: "अभी तक कोई सिफारिश नहीं। अधिक खोजने के लिए अन्वेषण करें!"
    },
    Tamil: {
        welcome: "மீண்டும் வருக",
        plan: "உங்கள் சாகசம் காத்திருக்கிறது. இன்றைய திட்டம் என்ன?",
        explore: "ஆராயுங்கள்",
        newTrip: "புதிய பயணம் திட்டமிடுங்கள்",
        totalBudget: "மொத்த திட்டமிடப்பட்ட பட்ஜெட்",
        totalTrips: "மொத்த பயணங்கள்",
        avgCost: "சராசரி பயணச் செலவு",
        recentTrips: "சமீபத்திய பயணங்கள்",
        viewAll: "அனைத்தையும் காண்க",
        recommended: "உங்களுக்காக பரிந்துரைக்கப்படுகிறது",
        dashboard: "டாஷ்போர்டு",
        myTrips: "எனது பயணங்கள்",
        profile: "சுயவிவரம்",
        logout: "வெளியேறு",
        save: "சேமி",
        savedDest: "சேமிக்கப்பட்ட இடங்கள்",
        deleteAccount: "கணக்கை நீக்கு",
        editProfile: "சுயவிவரத்தைத் திருத்து",
        noTrips: "நீங்கள் இதுவரை எந்த பயணங்களையும் திட்டமிடவில்லை.",
        startAdventure: "உங்கள் முதல் சாகசத்தைத் தொடங்குங்கள்",
        manageItinerary: "பயணத் திட்டத்தை நிர்வகி",
        confirmDeleteAccount: "உங்கள் கணக்கை நிச்சயமாக நீக்க விரும்புகிறீர்களா? இதை செயல்தவிர்க்க முடியாது.",
        failedToDeleteAccount: "கணக்கை நீக்க முடியவில்லை",
        loadingProfile: "சுயவிவரம் ஏற்றப்படுகிறது...",
        userIcon: "பயனர் ஐகான்",
        noEmail: "மின்னஞ்சல் இல்லை",
        client: "வாடிக்கையாளர்",
        english: "ஆங்கிலம்",
        hindi: "இந்தி",
        tamil: "தமிழ்",
        telugu: "தெலுங்கு",
        malayalam: "மலையாளம்",
        kannada: "கன்னடம்",
        preview: "முன்னோட்டம்",
        fullName: "முழு பெயர்",
        languagePreference: "மொழி விருப்பம்",
        cancel: "ரத்துசெய்",
        saveChanges: "மாற்றங்களைச் சேமி",
        remove: "அகற்று",
        noSavedDestinations: "இதுவரை சேமிக்கப்பட்ட இடங்கள் இல்லை.",
        accountActions: "கணக்கு நடவடிக்கைகள்",
        deleteAccountWarning: "உங்கள் கணக்கை நீக்குவது உங்கள் அனைத்து பயணங்களையும் தரவுகளையும் நிரந்தரமாக அகற்றும்.",
        user: "பயனர்",
        manageAdventures: "உங்கள் திட்டமிடப்பட்ட அனைத்து சாகசங்களையும் நிர்வகிக்கவும்.",
        destinations: "இலக்குகள்",
        budgetLabel: "பட்ஜெட்:",
        deleteTrip: "பயணத்தை நீக்கு",
        editTrip: "பயணத்தைத் திருத்து",
        startPlanning: "திட்டமிடத் தொடங்குங்கள்",
        tripName: "பயணத்தின் பெயர்",
        tripDescPlaceholder: "எ.கா., ஐரோப்பாவில் கோடை 2024",
        description: "விளக்கம்",
        descPlaceholder: "உங்கள் பயணத்தை சுருக்கமாக விவரிக்கவும்...",
        startDate: "தொடக்க தேதி",

        // New Additions
        dailySpending: "தினசரி செலவு",
        noDailyData: "தினசரி தரவு இல்லை",
        costDistribution: "செலவு விநியோகம்",
        transport: "போக்குவரத்து",
        other: "மற்றவை",
        accommodation: "தங்குமிடம்",
        food: "உணவு",
        shopping: "ஷாப்பிங்",
        sightseeing: "சுற்றுலா",
        adventure: "சாகசம்",
        relaxation: "ஓய்வு",
        flight: "விமானம்",
        train: "ரயில்",
        bus: "பேருந்து",
        car: "கார்",
        interactiveCalendar: "ஊடாடும் காலண்டர்",
        timeline: "காலவரிசை",
        arrivingBy: "வருவது",
        day: "நாள்",
        days: "நாட்கள்",
        yourItineraryEmpty: "உங்கள் பயணத் திட்டம் காலியாக உள்ளது. இடங்களைச் சேர்க்க டாஷ்போர்டுக்குச் செல்லவும்!",
        noItineraryData: "பயணத் திட்ட தரவு இல்லை.",
        startYourJourney: "உங்கள் பயணத்தைத் தொடங்குங்கள்",
        haventAddedDestinations: "நீங்கள் இன்னும் எந்த இடங்களையும் சேர்க்கவில்லை. திட்டமிடத் தொடங்க மேலே \"இலக்கைச் சேர்\" என்பதைக் கிளிக் செய்யவும்!",
        deleteActivityQuestion: "செயல்பாட்டை நீக்கவா?",
        deleteActivityConfirm: "இந்த செயல்பாட்டை நிச்சயமாக நீக்க விரும்புகிறீர்களா? இதை செயல்தவிர்க்க முடியாது.",
        removeDestinationQuestion: "இலக்கை அகற்றவா?",
        removeDestinationConfirm: "இந்த இலக்கை நிச்சயமாக அகற்ற விரும்புகிறீர்களா? தொடர்புடைய அனைத்து செயல்பாடுகளும் நீக்கப்படும்.",
        editActivity: "செயல்பாட்டைத் திருத்து",
        addNewActivity: "புதிய செயல்பாட்டைச் சேர்",
        editDestination: "இலக்கைத் திருத்து",
        confirm: "உறுதிப்படுத்து",
        cancel: "ரத்துசெய்",
        type: "வகை",
        notesOptional: "குறிப்புகள் (விருப்பத்தேர்வு)",
        cityName: "நகரத்தின் பெயர்",
        updateDestination: "இலக்கைப் புதுப்பி",
        unknownCity: "தெரியாத நகரம்",
        clickToAddActivity: "+ செயல்பாட்டைச் சேர்",
        deleteTripQuestion: "இந்த பயணத்தை நிச்சயமாக நீக்க விரும்புகிறீர்களா?",
        draft: "வரைவு",
        planned: "திட்டமிடப்பட்டது",
        manageItineraryArrow: "பயணத் திட்டத்தை நிர்வகி →",
        noTripsFound: "பயணங்கள் எதுவும் இல்லை",
        youHaventPlanned: "நீங்கள் இதுவரை எந்த பயணங்களையும் திட்டமிடவில்லை.",
        acrossActiveTrips: "அனைத்து செயலில் உள்ள பயணங்களிலும்",
        newRecently: "+ சமீபத்தில் புதியது",
        perItinerary: "பயணத் திட்டத்திற்கு",
        noRecommendations: "குறிப்பிட்ட பரிந்துரைகள் எதுவும் இல்லை. மேலும் அறிய ஆராயுங்கள்!",
        startTime: "தொடக்க நேரம்",
        endTime: "முடிவு நேரம்",
        dailySpending: "தினசரி செலவு",
        noDailyData: "தினசரி தரவு இல்லை",
        costDistribution: "செலவு விநியோகம்",
        transport: "போக்குவரத்து",
        other: "மற்றவை",
        accommodation: "தங்குமிடம்",
        food: "உணவு",
        shopping: "ஷாப்பிங்",
        sightseeing: "சுற்றிப் பார்த்தல்",
        adventure: "சாகசம்",
        relaxation: "ஓய்வு",
        flight: "விமானம்",
        train: "ரயில்",
        bus: "பேருந்து",
        car: "கார்",
        interactiveCalendar: "ஊடாடும் நாட்காட்டி",
        timeline: "காலவரிசை",
        arrivingBy: "மூலம் வருகை",
        day: "நாள்",
        days: "நாட்கள்",
        yourItineraryEmpty: "உங்கள் பயணத் திட்டம் காலியாக உள்ளது. இடங்களைச் சேர்க்க டாஷ்போர்டிற்குச் செல்லவும்!",
        noItineraryData: "பயணத் திட்டத் தரவு இல்லை.",
        startYourJourney: "உங்கள் பயணத்தைத் தொடங்குங்கள்",
        haventAddedDestinations: "நீங்கள் இன்னும் எந்த இடங்களையும் சேர்க்கவில்லை. திட்டமிடலைத் தொடங்க மேலே \"இடத்தைச் சேர்\" என்பதைக் கிளிக் செய்யவும்!",
        deleteActivityQuestion: "செயல்பாட்டை நீக்கவா?",
        deleteActivityConfirm: "இந்த செயல்பாட்டை நிச்சயமாக நீக்க விரும்புகிறீர்களா? இதை மீளமைக்க முடியாது.",
        removeDestinationQuestion: "இடத்தை நீக்கவா?",
        removeDestinationConfirm: "இந்த இடத்தை நிச்சயமாக நீக்க விரும்புகிறீர்களா? தொடர்புடைய அனைத்து செயல்பாடுகளும் நீக்கப்படும்.",
        editActivity: "செயல்பாட்டைத் திருத்து",
        addNewActivity: "புதிய செயல்பாட்டைச் சேர்",
        editDestination: "இடத்தைத் திருத்து",
        confirm: "உறுதிப்படுத்து",
        cancel: "ரத்துசெய்",
        type: "வகை",
        notesOptional: "குறிப்புகள் (விருப்பத்தேர்வு)",
        cityName: "நகரத்தின் பெயர்",
        updateDestination: "இடத்தைப் புதுப்பி",
        unknownCity: "தெரியாத நகரம்",
        clickToAddActivity: "+ செயல்பாட்டைச் சேர்",
        deleteTripQuestion: "நிச்சயமாக இந்தப் பயணத்தை நீக்க விரும்புகிறீர்களா?",
        draft: "வரைவு",
        planned: "திட்டமிடப்பட்டது",
        manageItineraryArrow: "பயணத் திட்டத்தை நிர்வகி →",
        noTripsFound: "பயணங்கள் எதுவும் இல்லை",
        youHaventPlanned: "நீங்கள் இதுவரை எந்த பயணங்களையும் திட்டமிடவில்லை.",
        acrossActiveTrips: "அனைத்து செயலில் உள்ள பயணங்களிலும்",
        newRecently: "+ சமீபத்தில் புதியது",
        perItinerary: "பயணத் திட்டத்திற்கு",
        noRecommendations: "குறிப்பிட்ட பரிந்துரைகள் எதுவும் இல்லை. மேலும் அறிய ஆராயுங்கள்!",

        endDate: "முடிவு தேதி",
        estBudget: "மதிப்பிடப்பட்ட பட்ஜெட்",
        coverPhoto: "அட்டைப் படம் (விருப்பத்தேர்வு)",
        creating: "உருவாக்குகிறது...",
        updateTrip: "பயணத்தைப் புதுப்பி",
        planNewTrip: "புதிய பயணத்தைத் திட்டமிடுங்கள்",
        updateTripDetails: "உங்கள் பயண விவரங்களைப் புதுப்பிக்கவும்.",
        startJourney: "அடிப்படைகளை வரையறுப்பதன் மூலம் உங்கள் பயணத்தைத் தொடங்குங்கள்.",
        itinerary: "பயணத் திட்டம்",
        budget: "பட்ஜெட்",
        calendar: "நாட்காட்டி",
        tripItinerary: "பயணத் திட்டம்",
        addDestination: "இலக்கைச் சேர்",
        addStop: "புதிய நிறுத்தத்தைச் சேர்",
        city: "நகரம்",
        searchCity: "நகரத்தைத் தேடு...",
        arrival: "வருகை",
        departure: "புறப்பாடு",
        saveStop: "நிறுத்தத்தைச் சேமி",
        removeStopConfirm: "இந்த நிறுத்தத்தை அகற்றவா?",
        activities: "செயல்பாடுகள்",
        addActivity: "செயல்பாட்டைச் சேர்",
        noActivities: "இதுவரை எந்த செயல்பாடுகளும் திட்டமிடப்படவில்லை.",
        startItinerary: "உங்கள் பயணத் திட்டத்தைத் தொடங்குங்கள்",
        addFirstDest: "தொடங்க உங்கள் முதல் இலக்கைச் சேர்க்கவும்.",
        activityName: "செயல்பாட்டின் பெயர்",
        cost: "செலவு ($)",
        category: "வகை",
        saveActivity: "செயல்பாட்டைச் சேமி",
        costDist: "செலவு விநியோகம்",
        budgetOverview: "பட்ஜெட் கண்ணோட்டம்",
        totalExpenses: "மொத்த செலவுகள்",
        remaining: "மீதமுள்ளது",
        tripTimeline: "பயண காலவரிசை",
        noStopsTimeline: "காலவரிசையில் காட்ட நிறுத்தங்கள் இல்லை.",
        exploreDest: "இலக்குகளை ஆராயுங்கள்",
        findPerfectCity: "உங்கள் அடுத்த சாகசத்திற்கான சரியான நகரத்தைக் கண்டறியவும்.",
        searchCityPlaceholder: "நகரத்தைத் தேடு (எ.கா., பாரிஸ், டோக்கியோ)...",
        costIndex: "செலவு குறியீடு:",
        cityDescDefault: "இந்த அற்புதமான இலக்கின் அழகையும் கலாச்சாரத்தையும் கண்டறியவும்.",
        planTripHere: "இங்கே பயணத்தைத் திட்டமிடுங்கள்",
        noCitiesFound: "பொருந்தும் நகரங்கள் எதுவும் இல்லை",
        loginWelcome: "மீண்டும் வருக",
        loginSubtitle: "GlobeTrotter இல் தொடர உள்நுழையவும்",
        emailLabel: "மின்னஞ்சல் முகவரி",
        emailPlaceholder: "ungal@email.com",
        passwordLabel: "கடவுச்சொல்",
        passwordPlaceholder: "••••••••",
        forgotPassword: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
        signIn: "உள்நுழைக",
        noAccount: "கணக்கு இல்லையா?",
        createAccount: "கணக்கை உருவாக்கு",
        createAccountTitle: "கணக்கை உருவாக்கு",
        verifyEmailTitle: "மின்னஞ்சலைச் சரிபார்",
        signupSubtitle: "GlobeTrotter உடன் உங்கள் பயணத்தைத் தொடங்குங்கள்",
        verifySubtitle: "தொடங்க ஒரு கடைசி படி",
        googleSignupFailed: "Google பதிவு தோல்வியடைந்தது",
        orSignupEmail: "அல்லது மின்னஞ்சல் மூலம் பதிவுபெறவும்",
        orLoginEmail: "அல்லது மின்னஞ்சல் மூலம் தொடரவும்",
        enterOtp: "OTP ஐ உள்ளிடவும்",
        otpPlaceholder: "6 இலக்க குறியீட்டை உள்ளிடவும்",
        verifyActivate: "சரிபார்த்து செயல்படுத்து",
        alreadyAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
        passRequirements: "8+ எழுத்துகள், 1 பெரிய எழுத்து, 1 எண், 1 சிறப்பு எழுத்து இருக்க வேண்டும்."
    },
    Telugu: {
        welcome: "తిరిగి స్వాగతం",
        plan: "మీ సాహసం వేచి ఉంది. ఈ రోజు ప్రణాళిక ఏమిటి?",
        explore: "అన్వేషించండి",
        newTrip: "కొత్త యాత్రను ప్లాన్ చేయండి",
        totalBudget: "మొత్తం ప్లాన్ చేసిన బడ్జెట్",
        totalTrips: "మొత్తం యాత్రలు",
        avgCost: "సగటు యాత్ర ఖర్చు",
        recentTrips: "ఇటీవలి యాత్రలు",
        viewAll: "అన్నింటినీ వీక్షించండి",
        recommended: "మీ కోసం సిఫార్సు చేయబడింది",
        dashboard: "డ్యాష్‌బోర్డ్",
        myTrips: "నా యాత్రలు",
        profile: "ప్రొఫైల్",
        logout: "లాగ్ అవుట్",
        save: "సేవ్ చేయి",
        savedDest: "సేవ్ చేసిన గమ్యస్థానాలు",
        deleteAccount: "ఖాతాను తొలగించు",
        editProfile: "ప్రొఫైల్‌ను సవరించు",
        noTrips: "మీరు ఇంకా ఏ యాత్రలను ప్లాన్ చేయలేదు.",
        startAdventure: "మీ మొదటి సాహసాన్ని ప్రారంభించండి",
        manageItinerary: "ప్రయాణ ప్రణాళికను నిర్వహించు",
        confirmDeleteAccount: "మీరు ఖచ్చితంగా మీ ఖాతాను తొలగించాలనుకుంటున్నారా? దీన్ని రద్దు చేయలేము.",
        failedToDeleteAccount: "ఖాతాను తొలగించడంలో విఫలమైంది",
        loadingProfile: "ప్రొఫైల్ లోడ్ అవుతోంది...",
        userIcon: "వినియోగదారు చిహ్నం",
        noEmail: "ఇమెయిల్ లేదు",
        client: "క్లయింట్",
        english: "ఆంగ్లం",
        hindi: "హిందీ",
        tamil: "తమిళం",
        telugu: "తెలుగు",
        malayalam: "మలయాళం",
        kannada: "కన్నడ",
        preview: "ముందస్తు వీక్షణ",
        fullName: "పూర్తి పేరు",
        languagePreference: "భాష ప్రాధాన్యత",
        cancel: "రద్దు చేయి",
        saveChanges: "మార్పులను సేవ్ చేయి",
        remove: "తొలగించు",
        noSavedDestinations: "ఇంకా సేవ్ చేసిన గమ్యస్థానాలు లేవు.",
        accountActions: "ఖాతా చర్యలు",
        deleteAccountWarning: "మీ ఖాతాను తొలగించడం వల్ల మీ అన్ని యాత్రలు మరియు డేటా శాశ్వతంగా తొలగించబడతాయి.",
        user: "వినియోగదారు",
        manageAdventures: "మీ అన్ని ప్లాన్ చేసిన సాహసాలను నిర్వహించండి.",
        destinations: "గమ్యస్థానాలు",
        budgetLabel: "బడ్జెట్:",
        deleteTrip: "యాత్రను తొలగించు",
        editTrip: "యాత్రను సవరించు",
        startPlanning: "ప్లానింగ్ ప్రారంభించండి",
        tripName: "యాత్ర పేరు",
        tripDescPlaceholder: "ఉదా., యూరప్‌లో వేసవి 2024",
        description: "వివరణ",
        descPlaceholder: "మీ యాత్రను క్లుప్తంగా వివరించండి...",
        startDate: "ప్రారంభ తేదీ",
        endDate: "ముగింపు తేదీ",
        estBudget: "అంచనా బడ్జెట్",
        coverPhoto: "కవర్ ఫోటో (ఐచ్ఛికం)",
        creating: "సృష్టిస్తోంది...",
        updateTrip: "యాత్రను నవీకరించు",
        planNewTrip: "కొత్త యాత్రను ప్లాన్ చేయండి",
        updateTripDetails: "మీ యాత్ర వివరాలను నవీకరించండి.",
        startJourney: "ప్రాథమికాలను నిర్వచించడం ద్వారా మీ ప్రయాణాన్ని ప్రారంభించండి.",
        itinerary: "ప్రయాణ ప్రణాళిక",
        budget: "బడ్జెట్",
        calendar: "క్యాలెండర్",
        tripItinerary: "యాత్ర ప్రయాణ ప్రణాళిక",
        addDestination: "గమ్యస్థానాన్ని జోడించు",
        addStop: "కొత్త స్టాప్‌ను జోడించు",
        city: "నగరం",
        searchCity: "నగరాన్ని శోధించు...",
        arrival: "రాక",
        departure: "నిష్క్రమణ",
        saveStop: "స్టాప్‌ను సేవ్ చేయి",
        removeStopConfirm: "ఈ స్టాప్‌ను తొలగించాలా?",
        activities: "కార్యకలాపాలు",
        addActivity: "కార్యకలాపాన్ని జోడించు",
        noActivities: "ఇంకా ఏ కార్యకలాపాలు ప్లాన్ చేయలేదు.",
        startItinerary: "మీ ప్రయాణ ప్రణాళికను ప్రారంభించండి",
        addFirstDest: "ప్రారంభించడానికి మీ మొదటి గమ్యస్థానాన్ని జోడించండి.",
        activityName: "కార్యకలాపం పేరు",
        cost: "ఖర్చు ($)",
        category: "వర్గం",
        saveActivity: "కార్యకలాపాన్ని సేవ్ చేయి",
        costDist: "ఖర్చు పంపిణీ",
        budgetOverview: "బడ్జెట్ అవలోకనం",
        totalExpenses: "మొత్తం ఖర్చులు",
        remaining: "మిగిలినవి",
        tripTimeline: "యాత్ర కాలక్రమం",
        noStopsTimeline: "కాలక్రమంలో చూపించడానికి స్టాప్‌లు లేవు.",
        exploreDest: "గమ్యస్థానాలను అన్వేషించండి",
        findPerfectCity: "మీ తదుపరి సాహసం కోసం సరైన నగరాన్ని కనుగొనండి.",
        searchCityPlaceholder: "నగరాన్ని శోధించండి (ఉదా., పారిస్, టోక్యో)...",
        costIndex: "ఖర్చు సూచిక:",
        cityDescDefault: "ఈ అద్భుతమైన గమ్యస్థానం యొక్క అందం మరియు సంస్కృతిని కనుగొనండి.",
        planTripHere: "ఇక్కడ యాత్రను ప్లాన్ చేయండి",
        noCitiesFound: "సరిపోలే నగరాలు ఏవీ కనుగొనబడలేదు",
        loginWelcome: "తిరిగి స్వాగతం",
        loginSubtitle: "GlobeTrotterకి కొనసాగడానికి సైన్ ఇన్ చేయండి",
        emailLabel: "ఇమెయిల్ చిరునామా",
        emailPlaceholder: "meeru@email.com",
        passwordLabel: "పాస్‌వర్డ్",
        passwordPlaceholder: "••••••••",
        forgotPassword: "పాస్‌వర్డ్ మర్చిపోయారా?",
        signIn: "సైన్ ఇన్",
        noAccount: "ఖాతా లేదా?",
        createAccount: "ఖాతాను సృష్టించు",
        createAccountTitle: "ఖాతాను సృష్టించు",
        verifyEmailTitle: "ఇమెయిల్‌ను ధృవీకరించు",
        signupSubtitle: "GlobeTrotterతో మీ ప్రయాణాన్ని ప్రారంభించండి",
        verifySubtitle: "ప్రారంభించడానికి చివరి దశ",
        googleSignupFailed: "Google సైన్అప్ విఫలమైంది",
        orSignupEmail: "లేదా ఇమెయిల్‌తో సైన్ అప్ చేయండి",
        orLoginEmail: "లేదా ఇమెయిల్‌తో కొనసాగండి",
        enterOtp: "OTP నమోదు చేయండి",
        otpPlaceholder: "6-అంకెల కోడ్‌ను నమోదు చేయండి",
        verifyActivate: "ధృవీకరించు & సక్రియం చేయి",
        alreadyAccount: "ఇప్పటికే ఖాతా ఉందా?",
        passRequirements: "8+ అక్షరాలు, 1 పెద్ద అక్షరం, 1 సంఖ్య, 1 ప్రత్యేక అక్షరం ఉండాలి.",

        // New Additions
        dailySpending: "రోజువారీ ఖర్చు",
        noDailyData: "రోజువారీ డేటా అందుబాటులో లేదు",
        costDistribution: "ఖర్చు పంపిణీ",
        transport: "రవాణా",
        other: "ఇతర",
        accommodation: "వసతి",
        food: "ఆహారం",
        shopping: "షాపింగ్",
        sightseeing: "సిటీ సీయింగ్",
        adventure: "సాహసం",
        relaxation: "విశ్రాంతి",
        flight: "విమానం",
        train: "రైలు",
        bus: "బస్సు",
        car: "కారు",
        interactiveCalendar: "ఇంటరాక్టివ్ క్యాలెండర్",
        timeline: "కాలక్రమం",
        arrivingBy: "ద్వారా రాక",
        day: "రోజు",
        days: "రోజులు",
        yourItineraryEmpty: "మీ ప్రయాణ ప్రణాళిక ఖాళీగా ఉంది. గమ్యస్థానాలను జోడించడానికి డాష్‌బోర్డ్‌కు వెళ్లండి!",
        noItineraryData: "ప్రయాణ ప్రణాళిక డేటా లేదు.",
        startYourJourney: "మీ ప్రయాణాన్ని ప్రారంభించండి",
        haventAddedDestinations: "మీరు ఇంకా ఏ గమ్యస్థానాలను జోడించలేదు. మీ యాత్రను ప్లాన్ చేయడం ప్రారంభించడానికి పైన \"గమ్యస్థానాన్ని జోడించు\" క్లిక్ చేయండి!",
        deleteActivityQuestion: "కార్యకలాపాన్ని తొలగించాలా?",
        deleteActivityConfirm: "మీరు ఖచ్చితంగా ఈ కార్యకలాపాన్ని తీసివేయాలనుకుంటున్నారా? దీన్ని రద్దు చేయలేము.",
        removeDestinationQuestion: "గమ్యస్థానాన్ని తీసివేయాలా?",
        removeDestinationConfirm: "మీరు ఖచ్చితంగా ఈ గమ్యస్థానాన్ని తీసివేయాలనుకుంటున్నారా? సంబంధిత అన్ని కార్యకలాపాలు తొలగించబడతాయి.",
        editActivity: "కార్యకలాపాన్ని సవరించు",
        addNewActivity: "కొత్త కార్యకలాపాన్ని జోడించు",
        editDestination: "గమ్యస్థానాన్ని సవరించు",
        confirm: "నిర్ధారించు",
        cancel: "రద్దు చేయి",
        type: "రకం",
        notesOptional: "గమనికలు (ఐచ్ఛికం)",
        cityName: "నగరం పేరు",
        updateDestination: "గమ్యస్థానాన్ని నవీకరించు",
        unknownCity: "తెలియని నగరం",
        clickToAddActivity: "+ కార్యకలాపాన్ని జోడించు",
        deleteTripQuestion: "మీరు ఖచ్చితంగా ఈ యాత్రను తొలగించాలనుకుంటున్నారా?",
        draft: "డ్రాఫ్ట్",
        planned: "ప్లాన్ చేసారు",
        manageItineraryArrow: "ప్రయాణ ప్రణాళిక నిర్వహణ →",
        noTripsFound: "ఏ యాత్రలు కనుగొనబడలేదు",
        noTripsFound: "ఏ యాత్రలు కనుగొనబడలేదు",
        youHaventPlanned: "మీరు ఇంకా ఏ యాత్రలను ప్లాన్ చేయలేదు.",
        acrossActiveTrips: "అన్ని క్రియాశీల యాత్రలలో",
        newRecently: "+ ఇటీవల కొత్తది",
        perItinerary: "ప్రతి ప్రయాణ ప్రణాళికకు",
        noRecommendations: "నిర్దిష్ట సిఫార్సులు ఏవీ లేవు. మరింత కనుగొనడానికి అన్వేషించండి!",
        startTime: "ప్రారంభ సమయం",
        endTime: "ముగింపు సమయం"
    },
    Kannada: {
        welcome: "ಮತ್ತೆ ಸುಸ್ವಾಗತ",
        plan: "ನಿಮ್ಮ ಸಾಹಸ ಕಾಯುತ್ತಿದೆ. ಇಂದಿನ ಯೋಜನೆ ಏನು?",
        explore: "ಅನ್ವೇಷಿಸಿ",
        newTrip: "ಹೊಸ ಯಾತ್ರೆಯನ್ನು ಯೋಜಿಸಿ",
        totalBudget: "ಒಟ್ಟು ಯೋಜಿತ ಬಜೆಟ್",
        totalTrips: "ಒಟ್ಟು ಯಾತ್ರೆಗಳು",
        avgCost: "ಸರಾಸರಿ ಯಾತ್ರೆ ವೆಚ್ಚ",
        recentTrips: "ಇತ್ತೀಚಿನ ಯಾತ್ರೆಗಳು",
        viewAll: "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
        recommended: "ನಿಮಗಾಗಿ ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ",
        dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        myTrips: "ನನ್ನ ಯಾತ್ರೆಗಳು",
        profile: "ಪ್ರೊಫೈಲ್",
        logout: "ಲಾಗ್ ಔಟ್",
        save: "ಉಳಿಸಿ",
        savedDest: "ಉಳಿಸಲಾದ ಗಮ್ಯಸ್ಥಾನಗಳು",
        deleteAccount: "ಖಾತೆಯನ್ನು ಅಳಿಸಿ",
        editProfile: "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
        noTrips: "ನೀವು ಇನ್ನೂ ಯಾವುದೇ ಯಾತ್ರೆಗಳನ್ನು ಯೋಜಿಸಿಲ್ಲ.",
        startAdventure: "ನಿಮ್ಮ ಮೊದಲ ಸಾಹಸವನ್ನು ಪ್ರಾರಂಭಿಸಿ",
        manageItinerary: "ಪ್ರವಾಸ ವಿವರವನ್ನು ನಿರ್ವಹಿಸಿ",
        confirmDeleteAccount: "ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ? ಇದನ್ನು ರದ್ದುಗೊಳಿಸಲಾಗುವುದಿಲ್ಲ.",
        failedToDeleteAccount: "ಖಾತೆಯನ್ನು ಅಳಿಸಲು ವಿಫಲವಾಗಿದೆ",
        loadingProfile: "ಪ್ರೊಫೈಲ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
        userIcon: "ಬಳಕೆದಾರ ಐಕಾನ್",
        noEmail: "ಇಮೇಲ್ ಇಲ್ಲ",
        client: "ಗ್ರಾಹಕ",
        english: "ಇಂಗ್ಲಿಷ್",
        hindi: "ಹಿಂದಿ",
        tamil: "ತಮಿಳು",
        telugu: "ತೆಲುಗು",
        malayalam: "ಮಲಯಾಳಂ",
        kannada: "ಕನ್ನಡ",
        preview: "ಮುನ್ನೋಟ",
        fullName: "ಪೂರ್ಣ ಹೆಸರು",
        languagePreference: "ಭಾಷಾ ಆದ್ಯತೆ",
        cancel: "ರದ್ದುಮಾಡಿ",
        saveChanges: "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
        remove: "ತೆಗೆದುಹಾಕಿ",
        noSavedDestinations: "ಇನ್ನೂ ಉಳಿಸಲಾದ ಗಮ್ಯಸ್ಥಾನಗಳಿಲ್ಲ.",
        accountActions: "ಖಾತೆ ಕ್ರಿಯೆಗಳು",
        deleteAccountWarning: "ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಅಳಿಸುವುದರಿಂದ ನಿಮ್ಮ ಎಲ್ಲಾ ಯಾತ್ರೆಗಳು ಮತ್ತು ಡೇಟಾವನ್ನು ಶಾಶ್ವತವಾಗಿ ತೆಗೆದುಹಾಕಲಾಗುತ್ತದೆ.",
        user: "ಬಳಕೆದಾರ",
        manageAdventures: "ನಿಮ್ಮ ಎಲ್ಲಾ ಯೋಜಿತ ಸಾಹಸಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
        destinations: "ಗಮ್ಯಸ್ಥಾನಗಳು",
        budgetLabel: "ಬಜೆಟ್:",
        deleteTrip: "ಯಾತ್ರೆಯನ್ನು ಅಳಿಸಿ",
        editTrip: "ಯಾತ್ರೆಯನ್ನು ಸಂಪಾದಿಸಿ",
        startPlanning: "ಯೋಜನೆ ಪ್ರಾರಂಭಿಸಿ",
        tripName: "ಯಾತ್ರೆಯ ಹೆಸರು",
        tripDescPlaceholder: "ಉದಾ., ಯುರೋಪ್‌ನಲ್ಲಿ ಬೇಸಿಗೆ 2024",
        description: "ವಿವರಣೆ",
        descPlaceholder: "ನಿಮ್ಮ ಯಾತ್ರೆಯನ್ನು ಸಂಕ್ಷಿಪ್ತವಾಗಿ ವಿವರಿಸಿ...",
        startDate: "ಪ್ರಾರಂಭ ದಿನಾಂಕ",
        endDate: "ಮುಕ್ತಾಯ ದಿನಾಂಕ",
        estBudget: "ಅಂದಾಜು ಬಜೆಟ್",
        coverPhoto: "ಕವರ್ ಫೋಟೋ (ಐಚ್ಛಿಕ)",
        creating: "ರಚಿಸಲಾಗುತ್ತಿದೆ...",
        updateTrip: "ಯಾತ್ರೆಯನ್ನು ನವೀಕರಿಸಿ",
        planNewTrip: "ಹೊಸ ಯಾತ್ರೆಯನ್ನು ಯೋಜಿಸಿ",
        updateTripDetails: "ನಿಮ್ಮ ಯಾತ್ರೆ ವಿವರಗಳನ್ನು ನವೀಕರಿಸಿ.",
        startJourney: "ಮೂಲಭೂತ ಅಂಶಗಳನ್ನು ವ್ಯಾಖ್ಯಾನಿಸುವ ಮೂಲಕ ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ.",
        itinerary: "ಪ್ರವಾಸ ವಿವರ",
        budget: "ಬಜೆಟ್",
        calendar: "ಕ್ಯಾಲೆಂಡರ್",
        tripItinerary: "ಯಾತ್ರೆ ಪ್ರವಾಸ ವಿವರ",
        addDestination: "ಗಮ್ಯಸ್ಥಾನವನ್ನು ಸೇರಿಸಿ",
        addStop: "ಹೊಸ ನಿಲ್ದಾಣವನ್ನು ಸೇರಿಸಿ",
        city: "ನಗರ",
        searchCity: "ನಗರವನ್ನು ಹುಡುಕಿ...",
        arrival: "ಆಗಮನ",
        departure: "ನಿರ್ಗಮನ",
        saveStop: "ನಿಲ್ದಾಣವನ್ನು ಉಳಿಸಿ",
        removeStopConfirm: "ಈ ನಿಲ್ದಾಣವನ್ನು ತೆಗೆದುಹಾಕುವುದೇ?",
        activities: "ಚಟುವಟಿಕೆಗಳು",
        addActivity: "ಚಟುವಟಿಕೆಯನ್ನು ಸೇರಿಸಿ",
        noActivities: "ಇನ್ನೂ ಯಾವುದೇ ಚಟುವಟಿಕೆಗಳನ್ನು ಯೋಜಿಸಲಾಗಿಲ್ಲ.",
        startItinerary: "ನಿಮ್ಮ ಪ್ರವಾಸ ವಿವರವನ್ನು ಪ್ರಾರಂಭಿಸಿ",
        addFirstDest: "ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಮೊದಲ ಗಮ್ಯಸ್ಥಾನವನ್ನು ಸೇರಿಸಿ.",
        activityName: "ಚಟುವಟಿಕೆಯ ಹೆಸರು",
        cost: "ವೆಚ್ಚ ($)",
        category: "ವರ್ಗ",
        saveActivity: "ಚಟುವಟಿಕೆಯನ್ನು ಉಳಿಸಿ",
        costDist: "ವೆಚ್ಚ ಹಂಚಿಕೆ",
        budgetOverview: "ಬಜೆಟ್ ಅವಲೋಕನ",
        totalExpenses: "ಒಟ್ಟು ವೆಚ್ಚಗಳು",
        remaining: "ಉಳಿದಿರುವುದು",
        tripTimeline: "ಯಾತ್ರೆ ಕಾಲಮಿತಿ",
        noStopsTimeline: "ಕಾಲಮಿತಿಯಲ್ಲಿ ತೋರಿಸಲು ಯಾವುದೇ ನಿಲ್ದಾಣಗಳಿಲ್ಲ.",
        exploreDest: "ಗಮ್ಯಸ್ಥಾನಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
        findPerfectCity: "ನಿಮ್ಮ ಮುಂದಿನ ಸಾಹಸಕ್ಕಾಗಿ ಸರಿಯಾದ ನಗರವನ್ನು ಕಂಡುಕೊಳ್ಳಿ.",
        searchCityPlaceholder: "ನಗರವನ್ನು ಹುಡುಕಿ (ಉದಾ., ಪ್ಯಾರಿಸ್, ಟೋಕಿಯೊ)...",
        costIndex: "ವೆಚ್ಚ ಸೂಚ್ಯಂಕ:",
        cityDescDefault: "ಈ ಅದ್ಭುತ ಗಮ್ಯస్థಾನದ ಸೌಂದರ್ಯ ಮತ್ತು ಸಂಸ್ಕೃತಿಯನ್ನು ಅನ್ವೇಷಿಸಿ.",
        planTripHere: "ಇಲ್ಲಿ ಯಾತ್ರೆಯನ್ನು ಯೋಜಿಸಿ",
        noCitiesFound: "ಯಾವುದೇ ಹೊಂದಾಣಿಕೆಯ ನಗರಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
        loginWelcome: "ಮತ್ತೆ ಸುಸ್ವಾಗತ",
        loginSubtitle: "GlobeTrotter ಗೆ ಮುಂದುವರಿಯಲು ಸೈನ್ ಇನ್ ಮಾಡಿ",
        emailLabel: "ಇಮೇಲ್ ವಿಳಾಸ",
        emailPlaceholder: "nimma@email.com",
        passwordLabel: "ಪಾಸ್‌ವರ್ಡ್",
        passwordPlaceholder: "••••••••",
        forgotPassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?",
        signIn: "ಸೈನ್ ಇನ್",
        noAccount: "ಖಾತೆ ಇಲ್ಲವೇ?",
        createAccount: "ಖಾತೆ ರಚಿಸಿ",
        createAccountTitle: "ಖಾತೆ ರಚಿಸಿ",
        verifyEmailTitle: "ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ",
        signupSubtitle: "GlobeTrotter ನೊಂದಿಗೆ ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ",
        verifySubtitle: "ಪ್ರಾರಂಭಿಸಲು ಒಂದು ಕೊನೆಯ ಹಂತ",
        googleSignupFailed: "Google ಸೈನ್ ಅಪ್ ವಿಫಲವಾಗಿದೆ",
        orSignupEmail: "ಅಥವಾ ಇಮೇಲ್ ಮೂಲಕ ಸೈನ್ ಅಪ್ ಮಾಡಿ",
        orLoginEmail: "ಅಥವಾ ಇಮೇಲ್ ಮೂಲಕ ಮುಂದುವರಿಯಿರಿ",
        enterOtp: "OTP ನಮೂದಿಸಿ",
        otpPlaceholder: "6-ಅಂಕಿಯ ಕೋಡ್ ನಮೂದಿಸಿ",
        verifyActivate: "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸಕ್ರಿಯಗೊಳಿಸಿ",
        alreadyAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
        passRequirements: "8+ ಅಕ್ಷರಗಳು, 1 ದೊಡ್ಡಕ್ಷರ, 1 ಸಂಖ್ಯೆ, 1 ವಿಶೇಷ ಅಕ್ಷರ ಇರಬೇಕು.",

        // New Additions
        dailySpending: "ದೈನಂದಿನ ಖರ್ಚು",
        noDailyData: "ದೈನಂದಿನ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ",
        costDistribution: "ವೆಚ್ಚ ವಿತರಣೆ",
        transport: "ಸಾರಿಗೆ",
        other: "ಇತರೆ",
        accommodation: "ವಸತಿ",
        food: "ಆಹಾರ",
        shopping: "ಶಾಪಿಂಗ್",
        sightseeing: "ನೋಡಬಹುದಾದ ಸ್ಥಳಗಳು",
        adventure: "ಸಾಹಸ",
        relaxation: "ವಿಶ್ರಾಂತಿ",
        flight: "ವಿಮಾನ",
        train: "ರೈಲು",
        bus: "ಬಸ್",
        car: "ಕಾರು",
        interactiveCalendar: "ಸಂವಾದಾತ್ಮಕ ಕ್ಯಾಲೆಂಡರ್",
        timeline: "ಕಾಲಮಿತಿ",
        arrivingBy: "ಮೂಲಕ ಆಗಮನ",
        day: "ದಿನ",
        days: "ದಿನಗಳು",
        yourItineraryEmpty: "ನಿಮ್ಮ ಪ್ರವಾಸ ವಿವರ ಖಾಲಿಯಾಗಿದೆ. ಗಮ್ಯಸ್ಥಾನಗಳನ್ನು ಸೇರಿಸಲು ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ!",
        noItineraryData: "ಪ್ರವಾಸ ವಿವರ ಡೇಟಾ ಇಲ್ಲ.",
        startYourJourney: "ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ",
        haventAddedDestinations: "ನೀವು ಇನ್ನೂ ಯಾವುದೇ ಗಮ್ಯಸ್ಥಾನಗಳನ್ನು ಸೇರಿಸಿಲ್ಲ. ಯೋಜನೆ ಪ್ರಾರಂಭಿಸಲು ಮೇಲೆ \"ಗಮ್ಯಸ್ಥಾನವನ್ನು ಸೇರಿಸಿ\" ಕ್ಲಿಕ್ ಮಾಡಿ!",
        deleteActivityQuestion: "ಚಟುವಟಿಕೆಯನ್ನು ಅಳಿಸುವುದೇ?",
        deleteActivityConfirm: "ನೀವು ಖಚಿತವಾಗಿ ಈ ಚಟುವಟಿಕೆಯನ್ನು ತೆಗೆದುಹಾಕಲು ಬಯಸುವಿರಾ? ಇದು ಬದಲಾಯಿಸಲಾಗದು.",
        removeDestinationQuestion: "ಗಮ್ಯಸ್ಥಾನವನ್ನು ತೆಗೆದುಹಾಕುವುದೇ?",
        removeDestinationConfirm: "ನೀವು ಖಚಿತವಾಗಿ ಈ ಗಮ್ಯಸ್ಥಾನವನ್ನು ತೆಗೆದುಹಾಕಲು ಬಯಸುವಿರಾ? ಸಂಬಂಧಿತ ಎಲ್ಲಾ ಚಟುವಟಿಕೆಗಳು ಅಳಿಸಲ್ಪಡುತ್ತವೆ.",
        editActivity: "ಚಟುವಟಿಕೆಯನ್ನು ಸಂಪಾದಿಸಿ",
        addNewActivity: "ಹೊಸ ಚಟುವಟಿಕೆಯನ್ನು ಸೇರಿಸಿ",
        editDestination: "ಗಮ್ಯಸ್ಥಾನವನ್ನು ಸಂಪಾದಿಸಿ",
        confirm: "ದೃಢೀಕರಿಸಿ",
        cancel: "ರದ್ದುಮಾಡಿ",
        type: "ಬಗೆ",
        notesOptional: "ಟಿಪ್ಪಣಿಗಳು (ಐಚ್ಛಿಕ)",
        cityName: "ನಗರದ ಹೆಸರು",
        updateDestination: "ಗಮ್ಯಸ್ಥಾನವನ್ನು ನವೀಕರಿಸಿ",
        unknownCity: "ಅಜ್ಞಾತ ನಗರ",
        clickToAddActivity: "+ ಚಟುವಟಿಕೆಯನ್ನು ಸೇರಿಸಿ",
        deleteTripQuestion: "ನೀವು ಖಚಿತವಾಗಿ ಈ ಯಾತ್ರೆಯನ್ನು ಅಳಿಸಲು ಬಯಸುವಿರಾ?",
        draft: "ಕರಡು",
        planned: "ಯೋಜಿಸಲಾಗಿದೆ",
        manageItineraryArrow: "ಪ್ರವಾಸ ವಿವರ ನಿರ್ವಹಣೆ →",
        noTripsFound: "ಯಾವುದೇ ಯಾತ್ರೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
        noTripsFound: "ಯಾವುದೇ ಯಾತ್ರೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
        youHaventPlanned: "ನೀವು ಇನ್ನೂ ಯಾವುದೇ ಯಾತ್ರೆಗಳನ್ನು ಯೋಜಿಸಿಲ್ಲ.",
        acrossActiveTrips: "ಎಲ್ಲಾ ಸಕ್ರಿಯ ಯಾತ್ರೆಗಳಲ್ಲಿ",
        newRecently: "+ ಇತ್ತೀಚೆಗೆ ಹೊಸದು",
        perItinerary: "ಪ್ರತಿ ಪ್ರವಾಸ ವಿವರಕ್ಕೆ",
        noRecommendations: "ಇನ್ನೂ ಯಾವುದೇ ನಿರ್ದಿಷ್ಟ ಶಿಫಾರಸುಗಳಿಲ್ಲ. ಇನ್ನಷ್ಟು ಹುಡುಕಲು ಅನ್ವೇಷಿಸಿ!",
        startTime: "ಪ್ರಾರಂಭದ ಸಮಯ",
        endTime: "ಅಂತ್ಯದ ಸಮಯ"
    },
    Malayalam: {
        welcome: "വീണ്ടും സ്വാഗതം",
        plan: "നിങ്ങളുടെ സാഹസികത കാത്തിരിക്കുന്നു. ഇന്നത്തെ പദ്ധതി എന്താണ്?",
        explore: "പര്യവേക്ഷണം ചെയ്യുക",
        newTrip: "പുതിയ യാത്ര ആസൂത്രണം ചെയ്യുക",
        totalBudget: "ആകെ ആസൂത്രണം ചെയ്ത ബജറ്റ്",
        totalTrips: "ആകെ യാത്രകൾ",
        avgCost: "ശരാശരി യാത്ര ചെലവ്",
        recentTrips: "സമീപകാല യാത്രകൾ",
        viewAll: "എല്ലാം കാണുക",
        recommended: "നിങ്ങൾക്കായി ശുപാർശ ചെയ്യുന്നത്",
        dashboard: "ഡാഷ്‌ബോർഡ്",
        myTrips: "എന്റെ യാത്രകൾ",
        profile: "പ്രൊഫൈൽ",
        logout: "ലോഗ് ഔട്ട്",
        save: "സംരക്ഷിക്കുക",
        savedDest: "സംരക്ഷിച്ച ലക്ഷ്യസ്ഥാനങ്ങൾ",
        deleteAccount: "അക്കൗണ്ട് ഇല്ലാതാക്കുക",
        editProfile: "പ്രൊഫൈൽ എഡിറ്റുചെയ്യുക",
        noTrips: "നിങ്ങൾ ഇതുവരെ യാത്രകളൊന്നും ആസൂത്രണം ചെയ്തിട്ടില്ല.",
        startAdventure: "നിങ്ങളുടെ ആദ്യത്തെ സാഹസികത ആരംഭിക്കുക",
        manageItinerary: "യാത്രാപരിപാടി നിയന്ത്രിക്കുക",
        confirmDeleteAccount: "നിങ്ങളുടെ അക്കൗണ്ട് ഇല്ലാതാക്കാൻ നിങ്ങൾ തീർച്ചയായും ആഗ്രഹിക്കുന്നുണ്ടോ? ഇത് തിരിച്ചെടുക്കാനാവില്ല.",
        failedToDeleteAccount: "അക്കൗണ്ട് ഇല്ലാതാക്കുന്നതിൽ പരാജയപ്പെട്ടു",
        loadingProfile: "പ്രൊഫൈൽ ലോഡുചെയ്യുന്നു...",
        userIcon: "ഉപയോക്തൃ ചിഹ്നം",
        noEmail: "ഇമെയിൽ ഇല്ല",
        client: "ക്ലയന്റ്",
        english: "ഇംഗ്ലീഷ്",
        hindi: "ഹിന്ദി",
        tamil: "തമിഴ്",
        telugu: "തെലുങ്ക്",
        malayalam: "മലയാളം",
        kannada: "കന്നഡ",
        preview: "പ്രിവ്യൂ",
        fullName: "പൂർണ്ണ പേര്",
        languagePreference: "ഭാഷാ മുൻഗണന",
        cancel: "റദ്ദാക്കുക",
        saveChanges: "മാറ്റങ്ങൾ സംരക്ഷിക്കുക",
        remove: "നീക്കംചെയ്യുക",
        noSavedDestinations: "ഇതുവരെ സംരക്ഷിച്ച ലക്ഷ്യസ്ഥാനങ്ങളില്ല.",
        accountActions: "അക്കൗണ്ട് പ്രവർത്തനങ്ങൾ",
        deleteAccountWarning: "നിങ്ങളുടെ അക്കൗണ്ട് ഇല്ലാതാക്കുന്നത് നിങ്ങളുടെ എല്ലാ യാത്രകളും ഡാറ്റയും ശാശ്വതമായി നീക്കംചെയ്യും.",
        user: "ഉപയോക്താവ്",
        manageAdventures: "നിങ്ങളുടെ ആസൂത്രണം ചെയ്ത എല്ലാ സാഹസികതകളും നിയന്ത്രിക്കുക.",
        destinations: "ലക്ഷ്യസ്ഥാനങ്ങൾ",
        budgetLabel: "ബജറ്റ്:",
        deleteTrip: "യാത്ര ഇല്ലാതാക്കുക",
        editTrip: "യാത്ര എഡിറ്റുചെയ്യുക",
        startPlanning: "ആസൂത്രണം ആരംഭിക്കുക",
        tripName: "യാത്രയുടെ പേര്",
        tripDescPlaceholder: "ഉദാഹരണത്തിന്, യൂറോപ്പിലെ വേനൽക്കാലം 2024",
        description: "വിവരണം",
        descPlaceholder: "നിങ്ങളുടെ യാത്ര ചുരുക്കത്തിൽ വിവരിക്കുക...",
        startDate: "തുടങ്ങുന്ന ദിവസം",
        endDate: "അവസാന തീയതി",
        estBudget: "കണക്കാക്കിയ ബജറ്റ്",
        coverPhoto: "കവർ ഫോട്ടോ (ഓപ്ഷണൽ)",
        creating: "സൃഷ്ടിക്കുന്നു...",
        updateTrip: "യാത്ര അപ്‌ഡേറ്റുചെയ്യുക",
        planNewTrip: "ഒരു പുതിയ യാത്ര ആസൂത്രണം ചെയ്യുക",
        updateTripDetails: "നിങ്ങളുടെ യാത്രയുടെ വിശദാംശങ്ങൾ അപ്‌ഡേറ്റുചെയ്യുക.",
        startJourney: "അടിസ്ഥാനങ്ങൾ നിർവചിച്ചുകൊണ്ട് നിങ്ങളുടെ യാത്ര ആരംഭിക്കുക.",
        itinerary: "യാത്രാപരിപാടി",
        budget: "ബജറ്റ്",
        calendar: "കലണ്ടർ",
        tripItinerary: "യാത്രാപരിപാടി",
        addDestination: "ലക്ഷ്യസ്ഥാനം ചേർക്കുക",
        addStop: "ഒരു പുതിയ സ്റ്റോപ്പ് ചേർക്കുക",
        city: "നഗരം",
        searchCity: "നഗരം തിരയുക...",
        arrival: "വരവ്",
        departure: "പുറപ്പെടൽ",
        saveStop: "സ്റ്റോപ്പ് സംരക്ഷിക്കുക",
        removeStopConfirm: "ഈ സ്റ്റോപ്പ് നീക്കംചെയ്യണോ?",
        activities: "പ്രവർത്തനങ്ങൾ",
        addActivity: "പ്രവർത്തനം ചേർക്കുക",
        noActivities: "ഇതുവരെ പ്രവർത്തനങ്ങളൊന്നും ആസൂത്രണം ചെയ്തിട്ടില്ല.",
        startItinerary: "നിങ്ങളുടെ യാത്രാപരിപാടി ആരംഭിക്കുക",
        addFirstDest: "ആരംഭിക്കുന്നതിന് നിങ്ങളുടെ ആദ്യ ലക്ഷ്യസ്ഥാനം ചേർക്കുക.",
        activityName: "പ്രവർത്തനത്തിന്റെ പേര്",
        cost: "ചെലവ് ($)",
        category: "വിഭാഗം",
        saveActivity: "പ്രവർത്തനം സംരക്ഷിക്കുക",
        costDist: "ചെലവ് വിതരണം",
        budgetOverview: "ബജറ്റ് അവലോകനം",
        totalExpenses: "ആകെ ചെലവുകൾ",
        remaining: "ബാക്കിയുള്ളവ",
        tripTimeline: "യാത്ര ടൈംലൈൻ",
        noStopsTimeline: "ടൈംലൈനിൽ കാണിക്കാൻ സ്റ്റോപ്പുകളില്ല.",
        exploreDest: "ലക്ഷ്യസ്ഥാനങ്ങൾ പര്യവേക്ഷണം ചെയ്യുക",
        findPerfectCity: "നിങ്ങളുടെ അടുത്ത സാഹസികതയ്ക്കായി ശരിയായ നഗരം കണ്ടെത്തുക.",
        searchCityPlaceholder: "നഗരം തിരയുക (ഉദാഹരണത്തിന്, പാരീസ്, ടോക്കിയോ)...",
        costIndex: "ചെലവ് സൂചിക:",
        cityDescDefault: "ഈ അത്ഭുതകരമായ ലക്ഷ്യസ്ഥാനത്തിന്റെ സൗന്ദര്യവും സംസ്കാരവും കണ്ടെത്തുക.",
        planTripHere: "ഇവിടെ യാത്ര ആസൂത്രണം ചെയ്യുക",
        noCitiesFound: "പൊരുത്തപ്പെടുന്ന നഗരങ്ങളൊന്നും കണ്ടെത്തിയില്ല",
        loginWelcome: "വീണ്ടും സ്വാഗതം",
        loginSubtitle: "GlobeTrotter-ലേക്ക് തുടരാൻ സൈൻ ഇൻ ചെയ്യുക",
        emailLabel: "ഇമെയിൽ വിലാസം",
        emailPlaceholder: "ningalude@email.com",
        passwordLabel: "പാസ്‌വേഡ്",
        passwordPlaceholder: "••••••••",
        forgotPassword: "പാസ്‌വേഡ് മറന്നോ?",
        signIn: "സൈൻ ഇൻ",
        noAccount: "അക്കൗണ്ട് ഇല്ലേ?",
        createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
        createAccountTitle: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
        verifyEmailTitle: "ഇമെയിൽ പരിശോധിക്കുക",
        signupSubtitle: "GlobeTrotter-നൊപ്പം നിങ്ങളുടെ യാത്ര ആരംഭിക്കുക",
        verifySubtitle: "ആരംഭിക്കുന്നതിന് ഒരു അവസാന ഘട്ടം",
        googleSignupFailed: "Google സൈൻ അപ്പ് പരാജയപ്പെട്ടു",
        orSignupEmail: "അല്ലെങ്കിൽ ഇമെയിൽ ഉപയോഗിച്ച് സൈൻ അപ്പ് ചെയ്യുക",
        orLoginEmail: "അല്ലെങ്കിൽ ഇമെയിൽ ഉപയോഗിച്ച് തുടരുക",
        enterOtp: "OTP നൽകുക",
        otpPlaceholder: "6-അക്ക കോഡ് നൽകുക",
        verifyActivate: "പരിശോധിച്ച് സജീവമാക്കുക",
        alreadyAccount: "ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?",
        passRequirements: "8+ പ്രതീകങ്ങൾ, 1 വലിയക്ഷരം, 1 നമ്പർ, 1 പ്രത്യേക പ്രതീകം ഉണ്ടായിരിക്കണം.",

        // New Additions
        dailySpending: "ദിവസേനയുള്ള ചെലവ്",
        noDailyData: "ദിവസേനയുള്ള ഡാറ്റ ലഭ്യമല്ല",
        costDistribution: "ചെലവ് വിതരണം",
        transport: "ഗതാഗതം",
        other: "മറ്റുള്ളവ",
        accommodation: "താമസം",
        food: "ഭക്ഷണം",
        shopping: "ഷോപ്പിംഗ്",
        sightseeing: "കാഴ്ചകൾ",
        adventure: "സാഹസികത",
        relaxation: "വിശ്രമം",
        flight: "വിമാനം",
        train: "ട്രെയിൻ",
        bus: "ബസ്",
        car: "കാർ",
        interactiveCalendar: "ഇന്ററാക്ടീവ് കലണ്ടർ",
        timeline: "സമയരേഖ",
        arrivingBy: "വഴിയുള്ള വരവ്",
        day: "ദിവസം",
        days: "ദിവസങ്ങൾ",
        yourItineraryEmpty: "നിങ്ങളുടെ യാത്രാപരിപാടി ശൂന്യമാണ്. ലക്ഷ്യസ്ഥാനങ്ങൾ ചേർക്കാൻ ഡാഷ്‌ബോർഡിലേക്ക് പോകുക!",
        noItineraryData: "യാത്രാപരിപാടി ഡാറ്റ ഇല്ല.",
        startYourJourney: "നിങ്ങളുടെ യാത്ര ആരംഭിക്കുക",
        haventAddedDestinations: "നിങ്ങൾ ഇതുവരെ ലക്ഷ്യസ്ഥാനങ്ങളൊന്നും ചേർത്തിട്ടില്ല. ആസൂത്രണം ആരംഭിക്കാൻ മുകളിൽ \"ലക്ഷ്യസ്ഥാനം ചേർക്കുക\" ക്ലിക്ക് ചെയ്യുക!",
        deleteActivityQuestion: "പ്രവർത്തനം ഇല്ലാതാക്കണോ?",
        deleteActivityConfirm: "ഈ പ്രവർത്തനം നീക്കംചെയ്യാൻ നിങ്ങൾ തീർച്ചയായും ആഗ്രഹിക്കുന്നുണ്ടോ? ഇത് തിരിച്ചെടുക്കാനാവില്ല.",
        removeDestinationQuestion: "ലക്ഷ്യസ്ഥാനം നീക്കംചെയ്യണോ?",
        removeDestinationConfirm: "ഈ ലക്ഷ്യസ്ഥാനം നീക്കംചെയ്യാൻ നിങ്ങൾ തീർച്ചയായും ആഗ്രഹിക്കുന്നുണ്ടോ? ബന്ധപ്പെട്ട എല്ലാ പ്രവർത്തനങ്ങളും ഇല്ലാതാക്കപ്പെടും.",
        editActivity: "പ്രവർത്തനം എഡിറ്റുചെയ്യുക",
        addNewActivity: "പുതിയ പ്രവർത്തനം ചേർക്കുക",
        editDestination: "ലക്ഷ്യസ്ഥാനം എഡിറ്റുചെയ്യുക",
        confirm: "സ്ഥിരീകരിക്കുക",
        cancel: "റദ്ദാക്കുക",
        type: "തരം",
        notesOptional: "കുറിപ്പുകൾ (ഓപ്ഷണൽ)",
        cityName: "നഗരത്തിന്റെ പേര്",
        updateDestination: "ലക്ഷ്യസ്ഥാനം അപ്‌ഡേറ്റുചെയ്യുക",
        unknownCity: "അജ്ഞാത നഗരം",
        clickToAddActivity: "+ പ്രവർത്തനം ചേർക്കുക",
        deleteTripQuestion: "ഈ യാത്ര ഇല്ലാതാക്കാൻ നിങ്ങൾ തീർച്ചയായും ആഗ്രഹിക്കുന്നുണ്ടോ?",
        draft: "കരട്",
        planned: "ആസൂത്രണം ചെയ്തു",
        manageItineraryArrow: "യാത്രാപരിപാടി നിയന്ത്രിക്കുക →",
        noTripsFound: "യാത്രകളൊന്നും കണ്ടെത്തിയില്ല",
        noTripsFound: "യാത്രകളൊന്നും കണ്ടെത്തിയില്ല",
        youHaventPlanned: "നിങ്ങൾ ഇതുവരെ യാത്രകളൊന്നും ആസൂത്രണം ചെയ്തിട്ടില്ല.",
        acrossActiveTrips: "സജീവമായ എല്ലാ യാത്രകളിലും",
        newRecently: "+ അടുത്തിടെ പുതിയത്",
        perItinerary: "ഓരോ യാത്രാപരിപാടിക്കും",
        noRecommendations: "ഇതുവരെ പ്രത്യേക ശുപാർശകളൊന്നുമില്ല. കൂടുതൽ കണ്ടെത്താൻ പര്യവേക്ഷണം ചെയ്യുക!",
        startTime: "ആരംഭ സമയം",
        endTime: "അവസാന സമയം"
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('English');
    const [user, setUser] = useState({});

    useEffect(() => {
        const storedUser = JSON.parse(localStorage.getItem('user') || '{}');
        const storedLang = localStorage.getItem('language');

        if (storedLang) {
            setLanguage(storedLang);
        } else if (storedUser.languagePreference) {
            setLanguage(storedUser.languagePreference);
        }
        setUser(storedUser);
    }, []);

    const changeLanguage = async (newLang) => {
        setLanguage(newLang);
        // Persist to local storage
        const storedUser = JSON.parse(localStorage.getItem('user') || '{}');
        storedUser.languagePreference = newLang;
        localStorage.setItem('user', JSON.stringify(storedUser));

        // Also set a standalone preference for non-logged in users or fallback
        localStorage.setItem('language', newLang);
    };

    const t = (key) => {
        return translations[language]?.[key] || translations['English'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
